/*
 * This file was automatically generated by FIXSTRS.
 * Any modifications will be lost next time this tool
 * is invoked.
 */

#define  STRINGS_ID         "FreeDOS STRINGS v3"
#define  STRINGS_ID_TRAILER 4


extern const char TEXT_ERROR_INVALID_SWITCH[];
#define  TEXT_ERROR_INVALID_SWITCH          0x00  /* @ 0x0000 */
extern const char TEXT_ERROR_INVALID_LSWITCH[];
#define  TEXT_ERROR_INVALID_LSWITCH         0x01  /* @ 0x0017 */
extern const char TEXT_ERROR_ILLFORMED_OPTION[];
#define  TEXT_ERROR_ILLFORMED_OPTION        0x02  /* @ 0x002e */
extern const char TEXT_ERROR_OPT_ARG[];
#define  TEXT_ERROR_OPT_ARG                 0x03  /* @ 0x0047 */
extern const char TEXT_ERROR_OPT_NOARG[];
#define  TEXT_ERROR_OPT_NOARG               0x04  /* @ 0x006d */
extern const char TEXT_INVALID_NUMBER[];
#define  TEXT_INVALID_NUMBER                0x05  /* @ 0x0090 */
extern const char TEXT_ERROR_CLOSE_QUOTE[];
#define  TEXT_ERROR_CLOSE_QUOTE             0x06  /* @ 0x00b2 */
extern const char TEXT_ERROR_TEMPFILE[];
#define  TEXT_ERROR_TEMPFILE                0x07  /* @ 0x00cd */
extern const char TEXT_ERROR_TOO_MANY_PARAMETERS_STR[];
#define  TEXT_ERROR_TOO_MANY_PARAMETERS_STR 0x08  /* @ 0x00ec */
extern const char TEXT_ERROR_TOO_MANY_PARAMETERS[];
#define  TEXT_ERROR_TOO_MANY_PARAMETERS     0x09  /* @ 0x0109 */
extern const char TEXT_ERROR_INVALID_PARAMETER[];
#define  TEXT_ERROR_INVALID_PARAMETER       0x0a  /* @ 0x011f */
extern const char TEXT_ERROR_PATH_NOT_FOUND[];
#define  TEXT_ERROR_PATH_NOT_FOUND          0x0b  /* @ 0x013a */
extern const char TEXT_ERROR_FILE_NOT_FOUND[];
#define  TEXT_ERROR_FILE_NOT_FOUND          0x0c  /* @ 0x014b */
extern const char TEXT_ERROR_SFILE_NOT_FOUND[];
#define  TEXT_ERROR_SFILE_NOT_FOUND         0x0d  /* @ 0x015c */
extern const char TEXT_ERROR_REQ_PARAM_MISSING[];
#define  TEXT_ERROR_REQ_PARAM_MISSING       0x0e  /* @ 0x0174 */
extern const char TEXT_ERROR_INVALID_DRIVE[];
#define  TEXT_ERROR_INVALID_DRIVE           0x0f  /* @ 0x0191 */
extern const char TEXT_ERROR_BADCOMMAND[];
#define  TEXT_ERROR_BADCOMMAND              0x10  /* @ 0x01a5 */
extern const char TEXT_ERROR_OUT_OF_MEMORY[];
#define  TEXT_ERROR_OUT_OF_MEMORY           0x11  /* @ 0x01c6 */
extern const char TEXT_ERROR_OUT_OF_DOS_MEMORY[];
#define  TEXT_ERROR_OUT_OF_DOS_MEMORY       0x12  /* @ 0x01dc */
extern const char TEXT_ERROR_CANNOTPIPE[];
#define  TEXT_ERROR_CANNOTPIPE              0x13  /* @ 0x01fe */
extern const char TEXT_ERROR_LONG_LINE_BATCHFILE[];
#define  TEXT_ERROR_LONG_LINE_BATCHFILE     0x14  /* @ 0x0229 */
extern const char TEXT_ERROR_BFILE_VANISHED[];
#define  TEXT_ERROR_BFILE_VANISHED          0x15  /* @ 0x0250 */
extern const char TEXT_ERROR_BFILE_LABEL[];
#define  TEXT_ERROR_BFILE_LABEL             0x16  /* @ 0x026b */
extern const char TEXT_ERROR_DIRFCT_FAILED[];
#define  TEXT_ERROR_DIRFCT_FAILED           0x17  /* @ 0x0298 */
extern const char TEXT_ERROR_SET_ENV_VAR[];
#define  TEXT_ERROR_SET_ENV_VAR             0x18  /* @ 0x02ad */
extern const char TEXT_ERROR_ENV_VAR_NOT_FOUND[];
#define  TEXT_ERROR_ENV_VAR_NOT_FOUND       0x19  /* @ 0x02e7 */
extern const char TEXT_ERROR_NO_ENVIRONMENT[];
#define  TEXT_ERROR_NO_ENVIRONMENT          0x1a  /* @ 0x030d */
extern const char TEXT_ERROR_SET_ALIAS[];
#define  TEXT_ERROR_SET_ALIAS               0x1b  /* @ 0x0345 */
extern const char TEXT_ERROR_ALIAS_NOT_FOUND[];
#define  TEXT_ERROR_ALIAS_NOT_FOUND         0x1c  /* @ 0x0370 */
extern const char TEXT_ERROR_NO_ALIAS_SEGMENT[];
#define  TEXT_ERROR_NO_ALIAS_SEGMENT        0x1d  /* @ 0x0387 */
extern const char TEXT_ERROR_SYNTAX_STR[];
#define  TEXT_ERROR_SYNTAX_STR              0x1e  /* @ 0x03ac */
extern const char TEXT_ERROR_SYNTAX[];
#define  TEXT_ERROR_SYNTAX                  0x1f  /* @ 0x03c2 */
extern const char TEXT_ERROR_FILENAME_TOO_LONG[];
#define  TEXT_ERROR_FILENAME_TOO_LONG       0x20  /* @ 0x03d1 */
extern const char TEXT_ERROR_SELFCOPY[];
#define  TEXT_ERROR_SELFCOPY                0x21  /* @ 0x03ec */
extern const char TEXT_ERROR_COMMAND_TOO_LONG[];
#define  TEXT_ERROR_COMMAND_TOO_LONG        0x22  /* @ 0x0408 */
extern const char TEXT_ERROR_LINE_TOO_LONG[];
#define  TEXT_ERROR_LINE_TOO_LONG           0x23  /* @ 0x0436 */
extern const char TEXT_ERROR_HISTORY_SIZE[];
#define  TEXT_ERROR_HISTORY_SIZE            0x24  /* @ 0x045f */
extern const char TEXT_HISTORY_EMPTY[];
#define  TEXT_HISTORY_EMPTY                 0x25  /* @ 0x047b */
extern const char TEXT_ERROR_BAD_MCB_CHAIN[];
#define  TEXT_ERROR_BAD_MCB_CHAIN           0x26  /* @ 0x0498 */
extern const char TEXT_ERROR_UNDEFINED_ERROR[];
#define  TEXT_ERROR_UNDEFINED_ERROR         0x27  /* @ 0x04cb */
extern const char TEXT_ERROR_REGION_WARNING[];
#define  TEXT_ERROR_REGION_WARNING          0x28  /* @ 0x04e0 */
extern const char TEXT_ERROR_ON_OR_OFF[];
#define  TEXT_ERROR_ON_OR_OFF               0x29  /* @ 0x0505 */
extern const char TEXT_ERROR_BAD_VARIABLE[];
#define  TEXT_ERROR_BAD_VARIABLE            0x2a  /* @ 0x051e */
extern const char TEXT_ERROR_IN_MISSING[];
#define  TEXT_ERROR_IN_MISSING              0x2b  /* @ 0x053b */
extern const char TEXT_ERROR_MISSING_PARENTHESES[];
#define  TEXT_ERROR_MISSING_PARENTHESES     0x2c  /* @ 0x054d */
extern const char TEXT_ERROR_DO_MISSING[];
#define  TEXT_ERROR_DO_MISSING              0x2d  /* @ 0x056f */
extern const char TEXT_ERROR_NO_COMMAND_AFTER_DO[];
#define  TEXT_ERROR_NO_COMMAND_AFTER_DO     0x2e  /* @ 0x0581 */
extern const char TEXT_ERROR_REDIRECT_FROM_FILE[];
#define  TEXT_ERROR_REDIRECT_FROM_FILE      0x2f  /* @ 0x05a6 */
extern const char TEXT_ERROR_REDIRECT_TO_FILE[];
#define  TEXT_ERROR_REDIRECT_TO_FILE        0x30  /* @ 0x05ce */
extern const char TEXT_ERROR_EMPTY_REDIRECTION[];
#define  TEXT_ERROR_EMPTY_REDIRECTION       0x31  /* @ 0x05f5 */
extern const char TEXT_ERROR_INVALID_DATE[];
#define  TEXT_ERROR_INVALID_DATE            0x32  /* @ 0x0609 */
extern const char TEXT_ERROR_INVALID_TIME[];
#define  TEXT_ERROR_INVALID_TIME            0x33  /* @ 0x0618 */
extern const char TEXT_ERROR_NO_GOTO_LABEL[];
#define  TEXT_ERROR_NO_GOTO_LABEL           0x34  /* @ 0x0627 */
extern const char TEXT_CTTY_NOTIMPLEMENTED[];
#define  TEXT_CTTY_NOTIMPLEMENTED           0x35  /* @ 0x0645 */
extern const char TEXT_ERROR_NORW_DEVICE[];
#define  TEXT_ERROR_NORW_DEVICE             0x36  /* @ 0x0680 */
extern const char TEXT_ERROR_CTTY_DUP[];
#define  TEXT_ERROR_CTTY_DUP                0x37  /* @ 0x06a7 */
extern const char TEXT_ERROR_L_NOTIMPLEMENTED[];
#define  TEXT_ERROR_L_NOTIMPLEMENTED        0x38  /* @ 0x06d7 */
extern const char TEXT_ERROR_U_NOTIMPLEMENTED[];
#define  TEXT_ERROR_U_NOTIMPLEMENTED        0x39  /* @ 0x06f0 */
extern const char TEXT_ERROR_WRITING_DEST[];
#define  TEXT_ERROR_WRITING_DEST            0x3a  /* @ 0x0709 */
extern const char TEXT_ERROR_CANNOT_OPEN_SOURCE[];
#define  TEXT_ERROR_CANNOT_OPEN_SOURCE      0x3b  /* @ 0x0728 */
extern const char TEXT_ERROR_OPEN_FILE[];
#define  TEXT_ERROR_OPEN_FILE               0x3c  /* @ 0x0747 */
extern const char TEXT_ERROR_READ_FILE[];
#define  TEXT_ERROR_READ_FILE               0x3d  /* @ 0x0761 */
extern const char TEXT_ERROR_WRITE_FILE[];
#define  TEXT_ERROR_WRITE_FILE              0x3e  /* @ 0x0780 */
extern const char TEXT_ERROR_LEADING_PLUS[];
#define  TEXT_ERROR_LEADING_PLUS            0x3f  /* @ 0x079e */
extern const char TEXT_ERROR_TRAILING_PLUS[];
#define  TEXT_ERROR_TRAILING_PLUS           0x40  /* @ 0x07da */
extern const char TEXT_ERROR_NOTHING_TO_DO[];
#define  TEXT_ERROR_NOTHING_TO_DO           0x41  /* @ 0x0817 */
extern const char TEXT_ERROR_COPY[];
#define  TEXT_ERROR_COPY                    0x42  /* @ 0x0827 */
extern const char TEXT_ERROR_IF_EXIST_NO_FILENAME[];
#define  TEXT_ERROR_IF_EXIST_NO_FILENAME    0x43  /* @ 0x0834 */
extern const char TEXT_ERROR_IF_ERRORLEVEL_NO_NUMBER[];
#define  TEXT_ERROR_IF_ERRORLEVEL_NO_NUMBER 0x44  /* @ 0x0850 */
extern const char TEXT_ERROR_IF_ERRORLEVEL_INVALID_NUMBER[];
#define  TEXT_ERROR_IF_ERRORLEVEL_INVALID_NUMBER 0x45  /* @ 0x086f */
extern const char TEXT_ERROR_IF_MISSING_COMMAND[];
#define  TEXT_ERROR_IF_MISSING_COMMAND      0x46  /* @ 0x088e */
extern const char TEXT_NOT_IMPLEMENTED_YET[];
#define  TEXT_NOT_IMPLEMENTED_YET           0x47  /* @ 0x08a3 */
extern const char TEXT_FAILED_LOAD_STRINGS[];
#define  TEXT_FAILED_LOAD_STRINGS           0x48  /* @ 0x08c1 */
extern const char TEXT_MSG_NOTIMPLEMENTED[];
#define  TEXT_MSG_NOTIMPLEMENTED            0x49  /* @ 0x08e7 */
extern const char TEXT_MSG_ITEMS_DISPLAYED[];
#define  TEXT_MSG_ITEMS_DISPLAYED           0x4a  /* @ 0x0921 */
extern const char TEXT_CORRUPT_COMMAND_LINE[];
#define  TEXT_CORRUPT_COMMAND_LINE          0x4b  /* @ 0x0936 */
extern const char TEXT_QUOTED_C_OR_K[];
#define  TEXT_QUOTED_C_OR_K                 0x4c  /* @ 0x09b3 */
extern const char TEXT_INIT_FULLY_QUALIFIED[];
#define  TEXT_INIT_FULLY_QUALIFIED          0x4d  /* @ 0x09ee */
extern const char TEXT_ERROR_RESTORE_SESSION[];
#define  TEXT_ERROR_RESTORE_SESSION         0x4e  /* @ 0x0a9e */
extern const char TEXT_ERROR_SAVE_SESSION[];
#define  TEXT_ERROR_SAVE_SESSION            0x4f  /* @ 0x0b30 */
extern const char TEXT_ERROR_CWD_FAILED[];
#define  TEXT_ERROR_CWD_FAILED              0x50  /* @ 0x0bc2 */
extern const char TEXT_ERROR_KSWAP_ALIAS_SIZE[];
#define  TEXT_ERROR_KSWAP_ALIAS_SIZE        0x51  /* @ 0x0bdd */
extern const char TEXT_ERROR_KSWAP_ALLOCMEM[];
#define  TEXT_ERROR_KSWAP_ALLOCMEM          0x52  /* @ 0x0c11 */
extern const char TEXT_ERROR_ALIAS_OUT_OF_MEM[];
#define  TEXT_ERROR_ALIAS_OUT_OF_MEM        0x53  /* @ 0x0c3f */
extern const char TEXT_ERROR_ALIAS_NO_SUCH[];
#define  TEXT_ERROR_ALIAS_NO_SUCH           0x54  /* @ 0x0c54 */
extern const char TEXT_ERROR_ALIAS_INSERT[];
#define  TEXT_ERROR_ALIAS_INSERT            0x55  /* @ 0x0c69 */
extern const char TEXT_ALIAS_INVALID_NAME[];
#define  TEXT_ALIAS_INVALID_NAME            0x56  /* @ 0x0c82 */
extern const char TEXT_ERROR_LOADING_CONTEXT[];
#define  TEXT_ERROR_LOADING_CONTEXT         0x57  /* @ 0x0c9c */
extern const char TEXT_ERROR_CONTEXT_OUT_OF_MEMORY[];
#define  TEXT_ERROR_CONTEXT_OUT_OF_MEMORY   0x58  /* @ 0x0cd3 */
extern const char TEXT_ERROR_CONTEXT_LENGTH[];
#define  TEXT_ERROR_CONTEXT_LENGTH          0x59  /* @ 0x0d54 */
extern const char TEXT_ERROR_CONTEXT_ADD_STATUS[];
#define  TEXT_ERROR_CONTEXT_ADD_STATUS      0x5a  /* @ 0x0dad */
extern const char TEXT_ERROR_CONTEXT_AFTER_SWAP[];
#define  TEXT_ERROR_CONTEXT_AFTER_SWAP      0x5b  /* @ 0x0e9f */
extern const char TEXT_ERROR_PERMISSION_DENIED[];
#define  TEXT_ERROR_PERMISSION_DENIED       0x5c  /* @ 0x0efd */
extern const char TEXT_ERROR_NO_SUCH_FILE[];
#define  TEXT_ERROR_NO_SUCH_FILE            0x5d  /* @ 0x0f14 */
extern const char TEXT_ERROR_UNKNOWN_ERROR[];
#define  TEXT_ERROR_UNKNOWN_ERROR           0x5e  /* @ 0x0f33 */
extern const char TEXT_MSG_PAUSE[];
#define  TEXT_MSG_PAUSE                     0x5f  /* @ 0x0f46 */
extern const char TEXT_MSG_HISTORY_SIZE[];
#define  TEXT_MSG_HISTORY_SIZE              0x60  /* @ 0x0f66 */
extern const char TEXT_MSG_DOSKEY[];
#define  TEXT_MSG_DOSKEY                    0x61  /* @ 0x0f81 */
extern const char TEXT_MSG_ECHO_STATE[];
#define  TEXT_MSG_ECHO_STATE                0x62  /* @ 0x0fb4 */
extern const char TEXT_MSG_VERIFY_STATE[];
#define  TEXT_MSG_VERIFY_STATE              0x63  /* @ 0x0fc0 */
extern const char TEXT_MSG_FDDEBUG_STATE[];
#define  TEXT_MSG_FDDEBUG_STATE             0x64  /* @ 0x0fce */
extern const char TEXT_MSG_FDDEBUG_TARGET[];
#define  TEXT_MSG_FDDEBUG_TARGET            0x65  /* @ 0x0fe3 */
extern const char TEXT_MSG_BREAK_STATE[];
#define  TEXT_MSG_BREAK_STATE               0x66  /* @ 0x1005 */
extern const char TEXT_MSG_LFNFOR_STATE[];
#define  TEXT_MSG_LFNFOR_STATE              0x67  /* @ 0x1012 */
extern const char TEXT_MSG_LFNFOR_COMPLETE_STATE[];
#define  TEXT_MSG_LFNFOR_COMPLETE_STATE     0x68  /* @ 0x1020 */
extern const char TEXT_MSG_CURRENT_DATE[];
#define  TEXT_MSG_CURRENT_DATE              0x69  /* @ 0x1034 */
extern const char TEXT_MSG_ENTER_DATE_AMERICAN[];
#define  TEXT_MSG_ENTER_DATE_AMERICAN       0x6a  /* @ 0x1048 */
extern const char TEXT_MSG_ENTER_DATE_EUROPE[];
#define  TEXT_MSG_ENTER_DATE_EUROPE         0x6b  /* @ 0x106a */
extern const char TEXT_MSG_ENTER_DATE_JAPANESE[];
#define  TEXT_MSG_ENTER_DATE_JAPANESE       0x6c  /* @ 0x108c */
extern const char TEXT_MSG_CURRENT_TIME[];
#define  TEXT_MSG_CURRENT_TIME              0x6d  /* @ 0x10ae */
extern const char TEXT_STRING_PM[];
#define  TEXT_STRING_PM                     0x6e  /* @ 0x10c2 */
extern const char TEXT_STRING_AM[];
#define  TEXT_STRING_AM                     0x6f  /* @ 0x10c6 */
extern const char TEXT_MSG_ENTER_TIME[];
#define  TEXT_MSG_ENTER_TIME                0x70  /* @ 0x10ca */
extern const char TEXT_MSG_COPYING[];
#define  TEXT_MSG_COPYING                   0x71  /* @ 0x10db */
extern const char PROMPT_DELETE_ALL[];
#define  PROMPT_DELETE_ALL                  0x72  /* @ 0x10e5 */
extern const char PROMPT_YES_NO[];
#define  PROMPT_YES_NO                      0x73  /* @ 0x112c */
extern const char PROMPT_CANCEL_BATCH[];
#define  PROMPT_CANCEL_BATCH                0x74  /* @ 0x1155 */
extern const char PROMPT_OVERWRITE_FILE[];
#define  PROMPT_OVERWRITE_FILE              0x75  /* @ 0x11b0 */
extern const char PROMPT_APPEND_FILE[];
#define  PROMPT_APPEND_FILE                 0x76  /* @ 0x11eb */
extern const char PROMPT_DELETE_FILE[];
#define  PROMPT_DELETE_FILE                 0x77  /* @ 0x1226 */
extern const char TEXT_UNKNOWN_FILENAME[];
#define  TEXT_UNKNOWN_FILENAME              0x78  /* @ 0x125e */
extern const char TEXT_DIRSTACK_EMPTY[];
#define  TEXT_DIRSTACK_EMPTY                0x79  /* @ 0x126a */
extern const char TEXT_DIR_HDR_VOLUME[];
#define  TEXT_DIR_HDR_VOLUME                0x7a  /* @ 0x1282 */
extern const char TEXT_DIR_HDR_VOLUME_STRING[];
#define  TEXT_DIR_HDR_VOLUME_STRING         0x7b  /* @ 0x1297 */
extern const char TEXT_DIR_HDR_VOLUME_NONE[];
#define  TEXT_DIR_HDR_VOLUME_NONE           0x7c  /* @ 0x129e */
extern const char TEXT_DIR_HDR_SERIAL_NUMBER[];
#define  TEXT_DIR_HDR_SERIAL_NUMBER         0x7d  /* @ 0x12ac */
extern const char TEXT_DIR_FTR_FILES[];
#define  TEXT_DIR_FTR_FILES                 0x7e  /* @ 0x12d0 */
extern const char TEXT_DIR_FTR_BYTES[];
#define  TEXT_DIR_FTR_BYTES                 0x7f  /* @ 0x12dd */
extern const char TEXT_DIR_FTR_TOTAL_NUMBER[];
#define  TEXT_DIR_FTR_TOTAL_NUMBER          0x80  /* @ 0x12ec */
extern const char TEXT_DIR_FTR_DIRS[];
#define  TEXT_DIR_FTR_DIRS                  0x81  /* @ 0x1301 */
extern const char TEXT_DIR_FTR_BYTES_FREE[];
#define  TEXT_DIR_FTR_BYTES_FREE            0x82  /* @ 0x130d */
extern const char TEXT_DIR_DIRECTORY[];
#define  TEXT_DIR_DIRECTORY                 0x83  /* @ 0x131f */
extern const char TEXT_DIR_DIRECTORY_WITH_SPACE[];
#define  TEXT_DIR_DIRECTORY_WITH_SPACE      0x84  /* @ 0x1330 */
extern const char TEXT_DIR_LINE_FILENAME_WIDE[];
#define  TEXT_DIR_LINE_FILENAME_WIDE        0x85  /* @ 0x1342 */
extern const char TEXT_DIR_LINE_FILENAME_BARE[];
#define  TEXT_DIR_LINE_FILENAME_BARE        0x86  /* @ 0x1348 */
extern const char TEXT_DIR_LINE_FILENAME_SINGLE[];
#define  TEXT_DIR_LINE_FILENAME_SINGLE      0x87  /* @ 0x134c */
extern const char TEXT_DIR_LINE_FILENAME[];
#define  TEXT_DIR_LINE_FILENAME             0x88  /* @ 0x1352 */
extern const char TEXT_DIR_LINE_SIZE_DIR[];
#define  TEXT_DIR_LINE_SIZE_DIR             0x89  /* @ 0x135d */
extern const char TEXT_DIR_LINE_SIZE[];
#define  TEXT_DIR_LINE_SIZE                 0x8a  /* @ 0x136c */
extern const char TEXT_FILE_COMPLATION_DISPLAY[];
#define  TEXT_FILE_COMPLATION_DISPLAY       0x8b  /* @ 0x1375 */
extern const char TEXT_MSG_PATH[];
#define  TEXT_MSG_PATH                      0x8c  /* @ 0x137b */
extern const char TEXT_MSG_PATH_NONE[];
#define  TEXT_MSG_PATH_NONE                 0x8d  /* @ 0x1384 */
extern const char TEXT_WEEKDAY_SHORT_NAME_SUNDAY[];
#define  TEXT_WEEKDAY_SHORT_NAME_SUNDAY     0x8e  /* @ 0x139d */
extern const char TEXT_WEEKDAY_SHORT_NAME_MONDAY[];
#define  TEXT_WEEKDAY_SHORT_NAME_MONDAY     0x8f  /* @ 0x13a1 */
extern const char TEXT_WEEKDAY_SHORT_NAME_TUESDAY[];
#define  TEXT_WEEKDAY_SHORT_NAME_TUESDAY    0x90  /* @ 0x13a5 */
extern const char TEXT_WEEKDAY_SHORT_NAME_WEDNSDAY[];
#define  TEXT_WEEKDAY_SHORT_NAME_WEDNSDAY   0x91  /* @ 0x13a9 */
extern const char TEXT_WEEKDAY_SHORT_NAME_THURSDAY[];
#define  TEXT_WEEKDAY_SHORT_NAME_THURSDAY   0x92  /* @ 0x13ad */
extern const char TEXT_WEEKDAY_SHORT_NAME_FRIDAY[];
#define  TEXT_WEEKDAY_SHORT_NAME_FRIDAY     0x93  /* @ 0x13b1 */
extern const char TEXT_WEEKDAY_SHORT_NAME_SATURDAY[];
#define  TEXT_WEEKDAY_SHORT_NAME_SATURDAY   0x94  /* @ 0x13b5 */
extern const char TEXT_MSG_DEL_CNT_FILES[];
#define  TEXT_MSG_DEL_CNT_FILES             0x95  /* @ 0x13b9 */
extern const char TEXT_MSG_DEL_CNT_FILES_1[];
#define  TEXT_MSG_DEL_CNT_FILES_1           0x96  /* @ 0x13cb */
extern const char TEXT_MSG_DEL_CNT_FILES_2[];
#define  TEXT_MSG_DEL_CNT_FILES_2           0x97  /* @ 0x13de */
extern const char TEXT_MSG_SHOWCMD_INTERNAL_COMMANDS[];
#define  TEXT_MSG_SHOWCMD_INTERNAL_COMMANDS 0x98  /* @ 0x13f1 */
extern const char TEXT_MSG_SHOWCMD_FEATURES[];
#define  TEXT_MSG_SHOWCMD_FEATURES          0x99  /* @ 0x140f */
extern const char TEXT_SHOWCMD_FEATURE_ALIASES[];
#define  TEXT_SHOWCMD_FEATURE_ALIASES       0x9a  /* @ 0x1425 */
extern const char TEXT_SHOWCMD_FEATURE_ENHANCED_INPUT[];
#define  TEXT_SHOWCMD_FEATURE_ENHANCED_INPUT 0x9b  /* @ 0x1430 */
extern const char TEXT_SHOWCMD_FEATURE_HISTORY[];
#define  TEXT_SHOWCMD_FEATURE_HISTORY       0x9c  /* @ 0x1442 */
extern const char TEXT_SHOWCMD_FEATURE_FILENAME_COMPLETION[];
#define  TEXT_SHOWCMD_FEATURE_FILENAME_COMPLETION 0x9d  /* @ 0x144d */
extern const char TEXT_SHOWCMD_FEATURE_SWAP_EXEC[];
#define  TEXT_SHOWCMD_FEATURE_SWAP_EXEC     0x9e  /* @ 0x1464 */
extern const char TEXT_SHOWCMD_FEATURE_CALL_LOGGING[];
#define  TEXT_SHOWCMD_FEATURE_CALL_LOGGING  0x9f  /* @ 0x1470 */
extern const char TEXT_SHOWCMD_FEATURE_LAST_DIR[];
#define  TEXT_SHOWCMD_FEATURE_LAST_DIR      0xa0  /* @ 0x1481 */
extern const char TEXT_SHOWCMD_FEATURE_LONG_FILENAMES[];
#define  TEXT_SHOWCMD_FEATURE_LONG_FILENAMES 0xa1  /* @ 0x148d */
extern const char TEXT_SHOWCMD_FEATURE_KERNEL_SWAP_SHELL[];
#define  TEXT_SHOWCMD_FEATURE_KERNEL_SWAP_SHELL 0xa2  /* @ 0x149f */
extern const char TEXT_SHOWCMD_FEATURE_XMS_SWAP[];
#define  TEXT_SHOWCMD_FEATURE_XMS_SWAP      0xa3  /* @ 0x14ae */
extern const char TEXT_SHOWCMD_DEFAULT_TO_SWAP[];
#define  TEXT_SHOWCMD_DEFAULT_TO_SWAP       0xa4  /* @ 0x14ba */
extern const char TEXT_SHOWCMD_FEATURE_INSTALLABLE_COMMANDS[];
#define  TEXT_SHOWCMD_FEATURE_INSTALLABLE_COMMANDS 0xa5  /* @ 0x14cd */
extern const char TEXT_SHOWCMD_FEATURE_NLS[];
#define  TEXT_SHOWCMD_FEATURE_NLS           0xa6  /* @ 0x14e5 */
extern const char TEXT_SHOWCMD_FEATURE_DIRSTACK[];
#define  TEXT_SHOWCMD_FEATURE_DIRSTACK      0xa7  /* @ 0x14f0 */
extern const char TEXT_SHOWCMD_FEATURE_DEBUG[];
#define  TEXT_SHOWCMD_FEATURE_DEBUG         0xa8  /* @ 0x150b */
extern const char TEXT_MSG_INIT_BYPASS_AUTOEXEC[];
#define  TEXT_MSG_INIT_BYPASS_AUTOEXEC      0xa9  /* @ 0x1520 */
extern const char TEXT_MSG_INIT_BYPASSING_AUTOEXEC[];
#define  TEXT_MSG_INIT_BYPASSING_AUTOEXEC   0xaa  /* @ 0x1551 */
extern const char TEXT_MSG_VER_DOS_VERSION[];
#define  TEXT_MSG_VER_DOS_VERSION           0xab  /* @ 0x1562 */
extern const char TEXT_MSG_VER_EARLY_FREEDOS[];
#define  TEXT_MSG_VER_EARLY_FREEDOS         0xac  /* @ 0x1577 */
extern const char TEXT_MSG_VER_LATER_FREEDOS[];
#define  TEXT_MSG_VER_LATER_FREEDOS         0xad  /* @ 0x159d */
extern const char TEXT_MSG_VER_WARRANTY[];
#define  TEXT_MSG_VER_WARRANTY              0xae  /* @ 0x15be */
extern const char TEXT_MSG_VER_REDISTRIBUTION[];
#define  TEXT_MSG_VER_REDISTRIBUTION        0xaf  /* @ 0x1755 */
extern const char TEXT_MSG_VER_DEVELOPERS[];
#define  TEXT_MSG_VER_DEVELOPERS            0xb0  /* @ 0x18f2 */
extern const char TEXT_MSG_REBOOT_NOW[];
#define  TEXT_MSG_REBOOT_NOW                0xb1  /* @ 0x19d7 */
extern const char TEXT_MSG_FREECOM_NOT_FOUND[];
#define  TEXT_MSG_FREECOM_NOT_FOUND         0xb2  /* @ 0x1abd */
extern const char TEXT_MEMORY_ENVIRONMENT[];
#define  TEXT_MEMORY_ENVIRONMENT            0xb3  /* @ 0x1b46 */
extern const char TEXT_MEMORY_CONTEXT[];
#define  TEXT_MEMORY_CONTEXT                0xb4  /* @ 0x1b7e */
extern const char TEXT_MEMORY_HEAP[];
#define  TEXT_MEMORY_HEAP                   0xb5  /* @ 0x1bb6 */
extern const char TEXT_MEMORY_CTXT_ALIAS[];
#define  TEXT_MEMORY_CTXT_ALIAS             0xb6  /* @ 0x1be0 */
extern const char TEXT_MEMORY_CTXT_HISTORY[];
#define  TEXT_MEMORY_CTXT_HISTORY           0xb7  /* @ 0x1c21 */
extern const char TEXT_MEMORY_CTXT_DIRSTACK[];
#define  TEXT_MEMORY_CTXT_DIRSTACK          0xb8  /* @ 0x1c62 */
extern const char TEXT_MEMORY_CTXT_LASTDIR[];
#define  TEXT_MEMORY_CTXT_LASTDIR           0xb9  /* @ 0x1ca3 */
extern const char TEXT_MEMORY_CTXT_BATCH[];
#define  TEXT_MEMORY_CTXT_BATCH             0xba  /* @ 0x1cd1 */
extern const char TEXT_MEMORY_CTXT_SWAPINFO[];
#define  TEXT_MEMORY_CTXT_SWAPINFO          0xbb  /* @ 0x1cff */
extern const char TEXT_ERROR_GET_CODEPAGE[];
#define  TEXT_ERROR_GET_CODEPAGE            0xbc  /* @ 0x1d2d */
extern const char TEXT_ERROR_SET_CODEPAGE[];
#define  TEXT_ERROR_SET_CODEPAGE            0xbd  /* @ 0x1d5f */
extern const char TEXT_DISPLAY_CODEPAGE[];
#define  TEXT_DISPLAY_CODEPAGE              0xbe  /* @ 0x1d84 */
extern const char TEXT_CMDHELP_ALIAS[];
#define  TEXT_CMDHELP_ALIAS                 0xbf  /* @ 0x1dc8 */
extern const char TEXT_CMDHELP_BEEP[];
#define  TEXT_CMDHELP_BEEP                  0xc0  /* @ 0x1eb4 */
extern const char TEXT_CMDHELP_BREAK[];
#define  TEXT_CMDHELP_BREAK                 0xc1  /* @ 0x1ec8 */
extern const char TEXT_CMDHELP_CALL[];
#define  TEXT_CMDHELP_CALL                  0xc2  /* @ 0x1f4a */
extern const char TEXT_CMDHELP_CD[];
#define  TEXT_CMDHELP_CD                    0xc3  /* @ 0x2087 */
extern const char TEXT_CMDHELP_CDD[];
#define  TEXT_CMDHELP_CDD                   0xc4  /* @ 0x2227 */
extern const char TEXT_CMDHELP_CHCP[];
#define  TEXT_CMDHELP_CHCP                  0xc5  /* @ 0x23be */
extern const char TEXT_CMDHELP_CLS[];
#define  TEXT_CMDHELP_CLS                   0xc6  /* @ 0x2467 */
extern const char TEXT_CMDHELP_COLOR[];
#define  TEXT_CMDHELP_COLOR                 0xc7  /* @ 0x2480 */
extern const char TEXT_CMDHELP_HELP[];
#define  TEXT_CMDHELP_HELP                  0xc8  /* @ 0x2546 */
extern const char TEXT_CMDHELP_COMMAND[];
#define  TEXT_CMDHELP_COMMAND               0xc9  /* @ 0x258c */
extern const char TEXT_CMDHELP_COPY[];
#define  TEXT_CMDHELP_COPY                  0xca  /* @ 0x2a19 */
extern const char TEXT_CMDHELP_CTTY[];
#define  TEXT_CMDHELP_CTTY                  0xcb  /* @ 0x2da6 */
extern const char TEXT_CMDHELP_DATE[];
#define  TEXT_CMDHELP_DATE                  0xcc  /* @ 0x2e2c */
extern const char TEXT_CMDHELP_DEL[];
#define  TEXT_CMDHELP_DEL                   0xcd  /* @ 0x2f05 */
extern const char TEXT_CMDHELP_DIR[];
#define  TEXT_CMDHELP_DIR                   0xce  /* @ 0x304a */
extern const char TEXT_CMDHELP_DOSKEY[];
#define  TEXT_CMDHELP_DOSKEY                0xcf  /* @ 0x3588 */
extern const char TEXT_CMDHELP_ORIGINAL_DOSKEY[];
#define  TEXT_CMDHELP_ORIGINAL_DOSKEY       0xd0  /* @ 0x3703 */
extern const char TEXT_CMDHELP_ECHO[];
#define  TEXT_CMDHELP_ECHO                  0xd1  /* @ 0x3c96 */
extern const char TEXT_CMDHELP_EXIT[];
#define  TEXT_CMDHELP_EXIT                  0xd2  /* @ 0x3d70 */
extern const char TEXT_CMDHELP_FOR[];
#define  TEXT_CMDHELP_FOR                   0xd3  /* @ 0x3dae */
extern const char TEXT_CMDHELP_GOTO[];
#define  TEXT_CMDHELP_GOTO                  0xd4  /* @ 0x3fe0 */
extern const char TEXT_CMDHELP_HISTORY[];
#define  TEXT_CMDHELP_HISTORY               0xd5  /* @ 0x40b6 */
extern const char TEXT_CMDHELP_IF[];
#define  TEXT_CMDHELP_IF                    0xd6  /* @ 0x4168 */
extern const char TEXT_CMDHELP_LFNFOR[];
#define  TEXT_CMDHELP_LFNFOR                0xd7  /* @ 0x44c1 */
extern const char TEXT_CMDHELP_LH[];
#define  TEXT_CMDHELP_LH                    0xd8  /* @ 0x459a */
extern const char TEXT_CMDHELP_LOADFIX[];
#define  TEXT_CMDHELP_LOADFIX               0xd9  /* @ 0x48c0 */
extern const char TEXT_CMDHELP_MD[];
#define  TEXT_CMDHELP_MD                    0xda  /* @ 0x49a2 */
extern const char TEXT_CMDHELP_PATH[];
#define  TEXT_CMDHELP_PATH                  0xdb  /* @ 0x49dc */
extern const char TEXT_CMDHELP_PAUSE[];
#define  TEXT_CMDHELP_PAUSE                 0xdc  /* @ 0x4ae3 */
extern const char TEXT_CMDHELP_PROMPT[];
#define  TEXT_CMDHELP_PROMPT                0xdd  /* @ 0x4b78 */
extern const char TEXT_CMDHELP_PUSHD[];
#define  TEXT_CMDHELP_PUSHD                 0xde  /* @ 0x4ddc */
extern const char TEXT_CMDHELP_POPD[];
#define  TEXT_CMDHELP_POPD                  0xdf  /* @ 0x4e97 */
extern const char TEXT_CMDHELP_DIRS[];
#define  TEXT_CMDHELP_DIRS                  0xe0  /* @ 0x4f12 */
extern const char TEXT_CMDHELP_RD[];
#define  TEXT_CMDHELP_RD                    0xe1  /* @ 0x4f47 */
extern const char TEXT_CMDHELP_REM[];
#define  TEXT_CMDHELP_REM                   0xe2  /* @ 0x4f92 */
extern const char TEXT_CMDHELP_REN[];
#define  TEXT_CMDHELP_REN                   0xe3  /* @ 0x4fdc */
extern const char TEXT_CMDHELP_SET[];
#define  TEXT_CMDHELP_SET                   0xe4  /* @ 0x5117 */
extern const char TEXT_CMDHELP_SHIFT[];
#define  TEXT_CMDHELP_SHIFT                 0xe5  /* @ 0x5438 */
extern const char TEXT_CMDHELP_TIME[];
#define  TEXT_CMDHELP_TIME                  0xe6  /* @ 0x54de */
extern const char TEXT_CMDHELP_TRUENAME[];
#define  TEXT_CMDHELP_TRUENAME              0xe7  /* @ 0x55c2 */
extern const char TEXT_CMDHELP_TYPE[];
#define  TEXT_CMDHELP_TYPE                  0xe8  /* @ 0x5619 */
extern const char TEXT_CMDHELP_VER[];
#define  TEXT_CMDHELP_VER                   0xe9  /* @ 0x565c */
extern const char TEXT_CMDHELP_VERIFY[];
#define  TEXT_CMDHELP_VERIFY                0xea  /* @ 0x578b */
extern const char TEXT_CMDHELP_FDDEBUG[];
#define  TEXT_CMDHELP_FDDEBUG               0xeb  /* @ 0x5848 */
extern const char TEXT_CMDHELP_VOL[];
#define  TEXT_CMDHELP_VOL                   0xec  /* @ 0x5a26 */
extern const char TEXT_CMDHELP_QUESTION[];
#define  TEXT_CMDHELP_QUESTION              0xed  /* @ 0x5a76 */
extern const char TEXT_CMDHELP_WHICH[];
#define  TEXT_CMDHELP_WHICH                 0xee  /* @ 0x5b89 */
extern const char TEXT_CMDHELP_MEMORY[];
#define  TEXT_CMDHELP_MEMORY                0xef  /* @ 0x5be2 */
extern const char TEXT_ERROR_COPY_PLUS_DESTINATION[];
#define  TEXT_ERROR_COPY_PLUS_DESTINATION   0xf0  /* @ 0x5c25 */
extern const char TEXT_DELETE_FILE[];
#define  TEXT_DELETE_FILE                   0xf1  /* @ 0x5c63 */
extern const char TEXT_ERROR_WRITE_FILE_DISC_FULL[];
#define  TEXT_ERROR_WRITE_FILE_DISC_FULL    0xf2  /* @ 0x5c78 */
extern const char TEXT_COPY_COPIED_NO_END[];
#define  TEXT_COPY_COPIED_NO_END            0xf3  /* @ 0x5cc0 */
extern const char TEXT_COPY_COPIED[];
#define  TEXT_COPY_COPIED                   0xf4  /* @ 0x5cd4 */
extern const char TEXT_ERROR_FCOM_IS_DEVICE[];
#define  TEXT_ERROR_FCOM_IS_DEVICE          0xf5  /* @ 0x5ce8 */
extern const char TEXT_ERROR_FCOM_INVALID[];
#define  TEXT_ERROR_FCOM_INVALID            0xf6  /* @ 0x5d0a */
extern const char TEXT_ERROR_LOADING_STRINGS[];
#define  TEXT_ERROR_LOADING_STRINGS         0xf7  /* @ 0x5d4b */
extern const char TEXT_TERMINATING[];
#define  TEXT_TERMINATING                   0xf8  /* @ 0x5e49 */
extern const char TEXT_HIDDEN_CRITER[];
#define  TEXT_HIDDEN_CRITER                 0xf9  /* @ 0x5e5b */
extern const char TEXT_DISP_EXITCODE[];
#define  TEXT_DISP_EXITCODE                 0xfa  /* @ 0x5e83 */
extern const char TEXT_EXIT_REASON_NEG_1[];
#define  TEXT_EXIT_REASON_NEG_1             0xfb  /* @ 0x5eb0 */
extern const char TEXT_EXIT_REASON_0[];
#define  TEXT_EXIT_REASON_0                 0xfc  /* @ 0x5ebe */
extern const char TEXT_EXIT_REASON_1[];
#define  TEXT_EXIT_REASON_1                 0xfd  /* @ 0x5ed2 */
extern const char TEXT_EXIT_REASON_2[];
#define  TEXT_EXIT_REASON_2                 0xfe  /* @ 0x5ee7 */
extern const char TEXT_EXIT_REASON_3[];
#define  TEXT_EXIT_REASON_3                 0xff  /* @ 0x5f04 */
extern const char TEXT_ERROR_EXE_CORRUPT[];
#define  TEXT_ERROR_EXE_CORRUPT             0x100  /* @ 0x5f12 */

/* END OF FILE */
